### PR TITLE
bug in compileSparseDesignMatrix

### PR DESCRIPTION
**Pull request by jcbyts**
I believe there was a bug in compileSparseDesignMatrix with the calling of the stimHandle for each covariate (line 26). stimHandle takes (trial,expt), not (trial,nT)... it doesn't seem to matter because nT isn't used, but it seems wrong to me.

I started adding help documentation to addCovariateSpiketrain. This is not finished.

### CODE REVIEW

**Comment by memming** [comment]
Cool. You are correct. it takes expt.
- Please don't comment out bugs: can you remove the commented line and send another pull request?
- Also, `varargin` in the documentation is not recommended. Can you expand it? (optional)

**Comment by jcbyts** [comment]
yea. I'll get to it in a minute :)

**Comment by jcbyts** [comment]
Updated help. Deleted buggy line. Found another bug and fixed it.

**Comment by memming** [comment]
Thanks, Jake. This is awesome.

**Pull request merged**
